service: deadletter-watcher

provider:
  name: aws
  runtime: python3.8

  region: eu-west-2

package:
  exclude:
    - .github/**
    - event_trigger_deploy/**
    - LICENSE
    - README.md
    - requirements.md

functions:
  hello:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: listener
          method: post
    iamRoleStatements:
      - Effect: "Allow"
        Action: "secretsmanager:GetSecretValue"
        Resource: "arn:aws:secretsmanager:eu-west-2:*:secret:deadletter-watcher-secrets-XOWbaE"
  

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

custom:
  pythonRequirements:
    dockerizePip: non-linux