name: CD Deadletter Watcher

on:
  push:
    paths: 
      - 'deadletter_listener/**'
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Goto deadletter_listener directory
      run: |
        pwd
        cd ./deadletter_listener/
        pwd

    - name: Install dependencies using pipenv
      run: |
        pwd
        python -m pip install --upgrade pip pipenv
        pipenv sync --dev
        
    - name: Serverless install python-requirements plugin
      uses: serverless/github-action@master
      with:
        args: plugin install --name serverless-python-requirements    
    
    - name: Serverless Deploy to AWS
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEADLETTER_WATCHER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEADLETTER_WATCHER_AWS_SECRET_ACCESS_KEY }}
